# Deploy with helm install postgres bitnami/postgresql-ha -f kubernetes/postgresql/values.yaml
postgresql:
  # TODO: Use CI Secrets for username and password
  username: devel
  password: 12345
  database: db
  replicaCount: 2
  repmgrPassword: 12345
volumePermissions:
  enabled: true
persistence:
  size: 2Gi
  storageClass: manual
pgpool:
  childLifeTime: 0
clusterDomain: cluster.topiaas
