apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: topiaas-cert
  namespace: default
spec:
  # Secret names are always required.
  secretName: topiaas-ml-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - topiaas
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - topiaas.ml
  - www.topiaas.ml
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
