---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-worker
  labels:
    app: portal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-worker
  template:
    metadata:
      labels:
        app: portal-worker
    spec:
      containers:
        - name: portal-worker
          image: topiaas/portalworker:latest
          env:
            - name: APP_NAME
              value: Topiaas
            - name: FLASK_CONFIG
              value: production
            - name: REDISTOGO_URL
              value: "http://redis-cluster-master:6379"
            - name: DATABASE_USER
              value: devel
            - name: DATABASE_PORT
              value: "5432"
            - name: MAIL_SERVER
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              value: "topiaas.bot@gmail.com"
            - name: MAIL_PASSWORD
              value: "Topiaas123"
            - name: MAIL_USE_TLS
              value: "True"
            - name: DATABASE_SERVICE_NAME
              value: postgres-postgresql-ha-postgresql
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-postgresql-ha-postgresql
                  key: postgresql-password
            - name: SECRET_KEY
              value: sercet_key
