"""add_app_password

Revision ID: 0cb2f852864d
Revises: b10c02ce73f3
Create Date: 2021-06-15 16:27:54.779374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb2f852864d'
down_revision = 'b10c02ce73f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'password')
    # ### end Alembic commands ###
