"""Add_user_storage_files

Revision ID: 1fcb44103774
Revises: f72d9cf9e57a
Create Date: 2021-07-05 23:05:00.684954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fcb44103774'
down_revision = 'f72d9cf9e57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app', 'deploy_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('app', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'deployed'::character varying"))
    op.add_column('users', sa.Column('storage_files', sa.ARRAY(sa.String(length=64)), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_files')
    op.alter_column('app', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'deployed'::character varying"))
    op.alter_column('app', 'deploy_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
