"""add_app_instances

Revision ID: 423873969a8a
Revises: 5242b398fe0d_add_all_tables
Create Date: 2021-05-08 23:35:18.328861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423873969a8a'
down_revision = '5242b398fe0d_add_all_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('app_type', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('vcpu_limit', sa.Integer(), nullable=True),
    sa.Column('memory_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app')
    # ### end Alembic commands ###
