"""add_user_capcity_limits

Revision ID: 73f5d4b4f20c
Create Date: 2021-04-25 00:46:52.170668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73f5d4b4f20c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("memory_limit", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("vcpu_limit", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "vcpu_limit")
    op.drop_column("users", "memory_limit")
    # ### end Alembic commands ###
