"""add_app_instances

Revision ID: b10c02ce73f3
Revises: 5242b398fe0d_add_all_tables
Create Date: 2021-06-05 19:59:07.146367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b10c02ce73f3"
down_revision = "5242b398fe0d_add_all_tables"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("index", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("app_type", sa.String(length=64), nullable=True),
        sa.Column("url", sa.String(length=128), nullable=True),
        sa.Column("owner", sa.Integer(), nullable=True),
        sa.Column("cpu_limit", sa.Integer(), nullable=True),
        sa.Column("memory_limit", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "app_user_association",
        sa.Column("users_id", sa.Integer(), nullable=True),
        sa.Column("app_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["app.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["users.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_user_association")
    op.drop_table("app")
    # ### end Alembic commands ###
