"""add_deploy_ts

Revision ID: f72d9cf9e57a
Revises: 0cb2f852864d
Create Date: 2021-06-24 18:20:16.121449

"""
from alembic import op
import sqlalchemy as sa

from app.lib.enumeration import AppStatus


# revision identifiers, used by Alembic.
revision = "f72d9cf9e57a"
down_revision = "0cb2f852864d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app",
        sa.Column("delete_ts", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "app",
        sa.Column(
            "deploy_ts", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
    )
    op.add_column(
        "app",
        sa.Column(
            "state",
            sa.String(length=64),
            server_default=AppStatus.DEPLOYED.value,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "state")
    op.drop_column("app", "deploy_ts")
    op.drop_column("app", "delete_ts")
    # ### end Alembic commands ###
