apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  labels:
    name: {{ name }}
spec:
  selector:
    matchLabels:
      name:  {{ name }}
  template:
    metadata:
      labels:
        name: {{ name }}
    spec:
      containers:
        - name: {{ name }}
          image: {{ image }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limit:
              cpu: {{ cpu_limit }}m
              memory: {{ memory_limit }}Mi
          ports:
            - containerPort: {{ port }}
          env:
            - name: PASSWORD
              value: {{ password }}

          # livenessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 90
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10
