---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-worker
  labels:
    app: portal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-worker
  template:
    metadata:
      labels:
        app: portal-worker
    spec:
      # must run kubectl label nodes topiaas dev=live
      # used because of mounted volumes being empty in secondary nodes (minikube bug)
      nodeSelector:
        dev: live
      serviceAccountName: app-manager-service-account
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: portal-worker
          image: topiaas/portal:latest
          imagePullPolicy: IfNotPresent
          command:
            - "python"
          args:
            - "-u"
            - "manage.py"
            - "run_worker"
          env:
            - name: APP_NAME
              value: Topiaas
            - name: FLASK_CONFIG
              value: development
            - name: REDISTOGO_URL
              value: "http://redis-service:6379"
            - name: MAIL_SERVER
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              value: "topiaas.bot@gmail.com"
            - name: MAIL_PASSWORD
              value: "Topiaas123"
            - name: MAIL_USE_TLS
              value: "True"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              value: sercet_key
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /app
              name: portalsrc
      volumes:
        - name: portalsrc
          hostPath:
            path: /app
